package com.ring.ytjojo.download;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ring.ytjojo.download.FileEntity;
import com.ring.ytjojo.download.ThreadEntity;

import com.ring.ytjojo.download.FileEntityDao;
import com.ring.ytjojo.download.ThreadEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileEntityDaoConfig;
    private final DaoConfig threadEntityDaoConfig;

    private final FileEntityDao fileEntityDao;
    private final ThreadEntityDao threadEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileEntityDaoConfig = daoConfigMap.get(FileEntityDao.class).clone();
        fileEntityDaoConfig.initIdentityScope(type);

        threadEntityDaoConfig = daoConfigMap.get(ThreadEntityDao.class).clone();
        threadEntityDaoConfig.initIdentityScope(type);

        fileEntityDao = new FileEntityDao(fileEntityDaoConfig, this);
        threadEntityDao = new ThreadEntityDao(threadEntityDaoConfig, this);

        registerDao(FileEntity.class, fileEntityDao);
        registerDao(ThreadEntity.class, threadEntityDao);
    }
    
    public void clear() {
        fileEntityDaoConfig.getIdentityScope().clear();
        threadEntityDaoConfig.getIdentityScope().clear();
    }

    public FileEntityDao getFileEntityDao() {
        return fileEntityDao;
    }

    public ThreadEntityDao getThreadEntityDao() {
        return threadEntityDao;
    }

}
