package com.ring.ytjojo.download;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FILE_ENTITY.
 */
public class FileEntity {

    private long id;
    private String url;
    private String path;
    private Long length;
    private Integer threads;
    private Boolean range;
    private Boolean isSucess;

    public FileEntity() {
    }

    public FileEntity(long id) {
        this.id = id;
    }

    public FileEntity(long id, String url, String path, Long length, Integer threads, Boolean range, Boolean isSucess) {
        this.id = id;
        this.url = url;
        this.path = path;
        this.length = length;
        this.threads = threads;
        this.range = range;
        this.isSucess = isSucess;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Long getLength() {
        return length;
    }

    public void setLength(Long length) {
        this.length = length;
    }

    public Integer getThreads() {
        return threads;
    }

    public void setThreads(Integer threads) {
        this.threads = threads;
    }

    public Boolean getRange() {
        return range;
    }

    public void setRange(Boolean range) {
        this.range = range;
    }

    public Boolean getIsSucess() {
        return isSucess;
    }

    public void setIsSucess(Boolean isSucess) {
        this.isSucess = isSucess;
    }

	public boolean isAgain() {
		// TODO Auto-generated method stub
		return false;
	}

}
