package com.ring.ytjojo.download;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table THREAD_ENTITY.
 */
public class ThreadEntity {

    private long id;
    private Long start;
    private Long end;
    private Long load;

    public ThreadEntity() {
    }

    public ThreadEntity(long id) {
        this.id = id;
    }

    public ThreadEntity(long id, Long start, Long end, Long load) {
        this.id = id;
        this.start = start;
        this.end = end;
        this.load = load;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Long getStart() {
        return start;
    }

    public void setStart(Long start) {
        this.start = start;
    }

    public Long getEnd() {
        return end;
    }

    public void setEnd(Long end) {
        this.end = end;
    }

    public Long getLoad() {
        return load;
    }

    public void setLoad(Long load) {
        this.load = load;
    }

	public void setFileEntity(FileEntity entity) {
		// TODO Auto-generated method stub
		
	}

}
