//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.ring.ytjojo.fragment;

import android.os.Bundle;
import android.support.v4.view.ViewPager;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import com.example.randomringapp.R.layout;
import com.ring.widget.PagerSlidingTabStrip;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ContentFragment_
    extends com.ring.ytjojo.fragment.ContentFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.layout_content, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ContentFragment_.FragmentBuilder_ builder() {
        return new ContentFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        pagerSlidingTabStrip = ((PagerSlidingTabStrip) hasViews.findViewById(com.example.randomringapp.R.id.slidingTabStrip_2));
        vp = ((ViewPager) hasViews.findViewById(com.example.randomringapp.R.id.content_viewpager));
        init();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<ContentFragment_.FragmentBuilder_, com.ring.ytjojo.fragment.ContentFragment>
    {


        @Override
        public com.ring.ytjojo.fragment.ContentFragment build() {
            ContentFragment_ fragment_ = new ContentFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
