//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.ring.ytjojo.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.AdapterView.OnItemLongClickListener;
import android.widget.ListView;
import com.example.randomringapp.R.layout;
import com.ring.ytjojo.app.AppContext_;
import com.ring.ytjojo.model.Song;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class RingListFragment_
    extends com.ring.ytjojo.fragment.RingListFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;
    public final static String TYPE_ARG = "type";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.ringactivity, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectFragmentArguments_();
        app = AppContext_.getInstance();
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static RingListFragment_.FragmentBuilder_ builder() {
        return new RingListFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        mListview = ((ListView) hasViews.findViewById(com.example.randomringapp.R.id.chosenListView));
        if (mListview!= null) {
            mListview.setOnItemClickListener(new OnItemClickListener() {


                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                    RingListFragment_.this.chosenListViewItemClicked(((Song) parent.getAdapter().getItem(position)));
                }

            }
            );
            mListview.setOnItemLongClickListener(new OnItemLongClickListener() {


                @Override
                public boolean onItemLongClick(AdapterView<?> parent, View view, int position, long id) {
                    RingListFragment_.this.chosenListViewItemLongClicked(((Song) parent.getAdapter().getItem(position)));
                    return true;
                }

            }
            );
        }
        init();
    }

    private void injectFragmentArguments_() {
        Bundle args_ = getArguments();
        if (args_!= null) {
            if (args_.containsKey(TYPE_ARG)) {
                type = args_.getInt(TYPE_ARG);
            }
        }
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<RingListFragment_.FragmentBuilder_, com.ring.ytjojo.fragment.RingListFragment>
    {


        @Override
        public com.ring.ytjojo.fragment.RingListFragment build() {
            RingListFragment_ fragment_ = new RingListFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

        public RingListFragment_.FragmentBuilder_ type(int type) {
            args.putInt(TYPE_ARG, type);
            return this;
        }

    }

}
