//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.ring.ytjojo.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import com.example.randomringapp.R.layout;
import com.ring.ytjojo.app.AppContext_;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;
import zrc.widget.ZrcListView;

public final class SelectRingFragment_
    extends com.ring.ytjojo.fragment.SelectRingFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;
    public final static String M_AUDIO_PATH_TYPE_ARG = "mAudioPathType";
    public final static String M_FROM_TYPE_ARG = "mFromType";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.selectactivity, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectFragmentArguments_();
        app = AppContext_.getInstance();
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static SelectRingFragment_.FragmentBuilder_ builder() {
        return new SelectRingFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        mListView = ((ZrcListView) hasViews.findViewById(com.example.randomringapp.R.id.zListView));
        initView();
    }

    private void injectFragmentArguments_() {
        Bundle args_ = getArguments();
        if (args_!= null) {
            if (args_.containsKey(M_AUDIO_PATH_TYPE_ARG)) {
                mAudioPathType = args_.getInt(M_AUDIO_PATH_TYPE_ARG);
            }
            if (args_.containsKey(M_FROM_TYPE_ARG)) {
                mFromType = args_.getInt(M_FROM_TYPE_ARG);
            }
        }
    }

    @SuppressWarnings({
        "unchecked"
    })
    @Override
    public void asynQueryDataBase() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    SelectRingFragment_.super.asynQueryDataBase();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<SelectRingFragment_.FragmentBuilder_, com.ring.ytjojo.fragment.SelectRingFragment>
    {


        @Override
        public com.ring.ytjojo.fragment.SelectRingFragment build() {
            SelectRingFragment_ fragment_ = new SelectRingFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

        public SelectRingFragment_.FragmentBuilder_ mAudioPathType(int mAudioPathType) {
            args.putInt(M_AUDIO_PATH_TYPE_ARG, mAudioPathType);
            return this;
        }

        public SelectRingFragment_.FragmentBuilder_ mFromType(int mFromType) {
            args.putInt(M_FROM_TYPE_ARG, mFromType);
            return this;
        }

    }

}
